apiVersion: v1
kind: Namespace
metadata:
  name: sales-ms-ns
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  labels:
    backstage.io/kubernetes-id: gitops-cluster
  name: sales-ms-git-repo
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/my-backstage-demo/sales-ms
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    backstage.io/kubernetes-id: gitops-cluster
  name: sales-ms-kustomization
  namespace: pulumi-operator
spec:
  force: false
  interval: 1m
  retryInterval: 1m
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: sales-ms-git-repo
    namespace: flux-system
  targetNamespace: sales-ms-ns
