apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  labels:
    backstage.io/kubernetes-id: gitops-cluster
  name: alb-controller-repo
  namespace: flux-system
spec:
  interval: 1m
  provider: generic
  timeout: 60s
  url: https://aws.github.io/eks-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    backstage.io/kubernetes-id: gitops-cluster
  name: alb-controller-helm-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: aws-load-balancer-controller
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: alb-controller-repo
        namespace: flux-system
      version: 1.6.1
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 1m
  targetNamespace: aws-lb-controller
  values:
    podLabels:
      backstage.io/kubernetes-id: gitops-cluster
  valuesFrom:
  - kind: Secret
    name: aws-load-balancer-controller-values
    valuesKey: values.yaml

