apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  labels:
    backstage.io/kubernetes-id: gitops-cluster
  name: external-secrets-repo
  namespace: flux-system
spec:
  interval: 1m
  provider: generic
  timeout: 60s
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    backstage.io/kubernetes-id: gitops-cluster
  name: external-secrets-helm-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      interval: 1m
      sourceRef:
        kind: HelmRepository
        name: external-secrets-repo
        namespace: flux-system
      version: 0.9.13
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 1m
  targetNamespace: external-secrets
  values:
    commonLabels:
      backstage.io/kubernetes-id: gitops-cluster
