apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flux
  description: GitOps operator
  annotations:
    pulumi.com/project-slug: dirien/pulumi-backstage-flux-gitops-aws/dev
    backstage.io/kubernetes-namespace: flux-system
    backstage.io/kubernetes-id: gitops-cluster
spec:
  owner: infrastructure
  domain: gitops-platform
  type: service
  lifecycle: experimental
  system: gitops-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pulumi-operator
  description: Pulumi operator
  annotations:
    backstage.io/kubernetes-namespace: pulumi-operator
    backstage.io/kubernetes-id: gitops-cluster
spec:
  owner: infrastructure
  domain: gitops-platform
  type: service
  lifecycle: experimental
  system: gitops-system
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: gitops-platform
  description: GitOps Platform
spec:
  owner: infrastructure
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: external-secrets
  description: External Secrets operator
  annotations:
    backstage.io/kubernetes-namespace: external-secrets
    backstage.io/kubernetes-id: gitops-cluster
spec:
  owner: infrastructure
  domain: gitops-platform
  type: service
  lifecycle: experimental
  system: gitops-system
