apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  labels:
    backstage.io/kubernetes-id: gitops-cluster
  name: pulumi-backstage-flux-gitops-aws-git-repo
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/my-backstage-demo/pulumi-infrastructure
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  labels:
    backstage.io/kubernetes-id: gitops-cluster
  name: pulumi-backstage-flux-gitops-aws-kustomization
  namespace: pulumi-operator
spec:
  force: false
  interval: 1m
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: pulumi-backstage-flux-gitops-aws-git-repo
    namespace: flux-system
  targetNamespace: pulumi-operator
