apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: pulumi-operator
spec:
  provider:
    pulumi:
      organization: ediri
      environment: backstage-demo
      accessToken:
        secretRef:
          name: pulumi-access-token
          key: pulumi-access-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret
  namespace: pulumi-operator
spec:
  refreshInterval: 20s
  secretStoreRef:
    kind: SecretStore
    name: secret-store
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: aws.accessKeyId
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: aws.secretAccessKey
