apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: pulumi-operator
spec:
  provider:
    pulumi:
      organization: dirien
      environment: backstage-demo
      accessToken:
        secretRef:
          name: pulumi-access-token
          key: pulumi-access-token
