apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  labels:
    backstage.io/kubernetes-id: gitops-cluster
  name: crossplane-repo
  namespace: flux-system
spec:
  interval: 1m
  provider: generic
  timeout: 60s
  url: https://charts.crossplane.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    backstage.io/kubernetes-id: gitops-cluster
  name: crossplane-helm-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: crossplane
      interval: 1m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: crossplane-repo
        namespace: flux-system
      version: 1.14.0
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 1m
  targetNamespace: crossplane-system
  values:
    customLabels:
      backstage.io/kubernetes-id: gitops-cluster
